#ifndef ZITTELMENENGINE_GLOBAL_H
#define ZITTELMENENGINE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ZITTELMENENGINE_LIBRARY)
#  define ZITTELMENENGINESHARED_EXPORT Q_DECL_EXPORT
#else
#  define ZITTELMENENGINESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ZITTELMENENGINE_GLOBAL_H
